### ISSUE TITLE
Wrong scalac option suggested

### ISSUE THREAD

**Issue by tgodzik** [scalacenter/scala3-migrate#153]
![image](https://user-images.githubusercontent.com/3807253/111341509-dead5b80-8679-11eb-9000-a32df6d0a637.png)

Instead for Scala 3 it should be `-Xtarget:8`

**Comment by reibitto** [comment]
I wasn't sure if I should report this separately or bucket it into this one, but I also noticed some possible issues with the options suggested.

I'm not using `-Yrangepos` yet I get an X for that. Also, the `-Xfatal-warnings` suggestion seems backwards.

![image](https://user-images.githubusercontent.com/6395394/115927832-09cc6b80-a4c0-11eb-9e66-2c18dd000a2b.png)

**Comment by adpi2** [comment]
> I'm not using -Yrangepos yet I get an X for that
@reibitto in some cases a `scalacOptions` can be added by another setting or plugin. For instance `-Yrangepos` is added by `sbt-scala3-migrate` itself. The plugin needs it to run Scalafix in the `migrateSyntax` command.

So the good news is you don't need to do anything about it. But I don't really know how to make this clearer in the output because sometime `-Yrangepos` is added manually so people need to know it is not available anymore...

> the -Xfatal-warnings suggestion seems backwards.
That's true. All the `-W` and `-V` options were added in Scala 2.13 quite recently and unfortunately we don't have them yet in Scala 3. This is planned, but for now we have to do without them.

A good resource for comparing the Scala 3 and Scala 2.13 options is https://scalacenter.github.io/scala-3-migration-guide/docs/compiler-options/compiler-options-table.html
