### ISSUE TITLE
New release for RC2?

### ISSUE THREAD

**Issue by bblfish** [scalacenter/scala3-migrate#196]
I am trying to migrate code from scala 2.13 but scalaz is only now available for RC2. 
`scala3-migrate` is hardcoded to look for RC1 libs at present.

I tried to build from source, and change the plugin to 0.4.0-SNAPSHOT, then `publishLocal` but sbt does not seem to pick things up.

**Comment by bblfish** [comment]
the project I am trying to convert is https://github.com/bblfish/banana-rdf/tree/scala3 in case you want to try that out.

**Comment by bblfish** [comment]
Just making the obvious adjustments of `s/RC1/RC2/` one gets the following error

```
[error] /Volumes/Dev/Programming/Scala3/scala3-migrate/interfaces/compiler/src/main/java/compiler/interfaces/Scala3Driver.java:22:1: cannot find symbol
[error]   symbol:   variable _2
[error]   location: class scala.Option<scala.Tuple2<scala.collection.immutable.List<dotty.tools.io.AbstractFile>,dotty.tools.dotc.core.Contexts.Context>>
[error] driver.setup(args, initCtx())._2
```

**Comment by mlachkar** [comment]
Hello! thanks for reporting this. I will release a new version soon!

**Comment by mlachkar** [comment]
It should be released in v.0.3.3. Thanks again.
Actually, the error you had, it's because the API on the dotty side had changed. it was returning a tuple and now an Option of Tuple.
I just did a quick fix (.get) to get the tuple. Those methods are called from scala side with a Try, so it should not throw an exception.
