### ISSUE TITLE
Modules were resolved with conflicting cross-version suffixes in ProjectRef

### ISSUE THREAD

**Issue by nkcoder** [scalacenter/scala3-migrate#345]
First of all, I'd like to thank you for providing this tool for the migration. 

I'm trying to migrate a system from Scala 2.13 to Scala 3 with `scala3-migrate`.

I updated the `build.sbt` according to the instructions by running `migrate-libs projectId` . Then I run `migrate-libs projectId` again, all the libs are valid:
<img width="1782" alt="image" src="https://user-images.githubusercontent.com/1478520/182010791-f6b47b14-cba3-4e8a-9822-8e7f6fe8e830.png">

But when I try to compile the project, I got this error: `Modules were resolved with conflicting cross-version suffixes in ProjectRef`:
<img width="823" alt="image" src="https://user-images.githubusercontent.com/1478520/182010823-3112ea85-fc35-4b24-b5c5-1a4eb7ccf57b.png">

Is this expected? Or should I continue with `migrate-scalacOptions`, `migrate-syntax` and `migrate`, and finally try to compile again?

Environment:
- sbt: 1.6.2
- scala: 2.13.8
- JDK: 11.0.15

**Comment by adpi2** [comment]
Hello @nkcoder

This error means that some dependencies are declared twice, directly or transitively, on 2 different Scala versions. This is not valid, so you need to fix this problem before continuing the migration.

Here for instance, `specs2-cats_2.13` depends on `cats-effect_2.13` but `cats-effect_3` is also declared. It would be better to use `specs2-cats_3` by declaring:
```scala
"orgs.specs2" %% "specs2-cats" % "1.0.0-ALPHA-01"
```
instead of
```scala
"orgs.specs2" %% "specs2-cats" % "1.0.0-ALPHA-01" cross CrossVersion.fro3Use2.13
```

Unfortunately `circe-generic-extra` is not available for Scala 3, so you should maybe try to remove that dependency.

**Comment by adpi2** [comment]
In general it is better not to use `CrossVersion.for3Use2_13`

**Comment by nkcoder** [comment]
Hi @adpi2, `CrossVersion.for3Use2_13` is the output/suggestion of `migrate-libs project_id`, why shouldn't use it?

**Comment by adpi2** [comment]
The tool should recommend it only if there is no Scala 3 compatible versions. It is a last resort and it does not give any guarantee that it will work.

In your case `circe-generic-extras` and `specs2-mock` are not published for Scala 3, so the tool suggests to use `CrossVersion.for3Use2_13`. Unfortunately it cannot work because they depend respectively on `circe-core` and `specs2-core` which are published for Scala 3. This problem is briefly explained [here](https://docs.scala-lang.org/scala3/guides/migration/compatibility-classpath.html#interoperability-overview):

> This is permitted as long as all libraries are resolved to a single binary version: you can have lib-foo_3 and lib-bar_2.13 in the same classpath, but you cannot have lib-foo_3 and lib-foo_2.13.
