### ISSUE TITLE
Failed to run scalafix with ProcedureSyntax, fix.scala213.ExplicitNullaryEtaExpansion, fix.scala213.ParensAroundLambda, fix.scala213.ExplicitNonNullaryApply, fix.scala213.Any2StringAdd on because missing symbol: jdk.internal.HotSpotIntrinsicCandidate

### ISSUE THREAD

**Issue by lakinwecker** [scalacenter/scala3-migrate#419]
I am trying to use this tool to port a project to 2.13.11 (with warnings as errors).  I have followed the instructions at https://scalacenter.github.io/scala-3-migration-guide/docs/tooling/scala-3-migrate-plugin.html but am running into two errors. If I use jdk18+, I get an error about incompatible class version numbers. If I used jdk 17, I get:
``` Failed to run scalafix with ProcedureSyntax, fix.scala213.ExplicitNullaryEtaExpansion, fix.scala213.ParensAroundLambda, fix.scala213.ExplicitNonNullaryApply, fix.scala213.Any2StringAdd on /home/lakin/work-repos/playstrategy/lila/modules/tv/src/main/TvTrouper.scala because missing symbol: jdk.internal.HotSpotIntrinsicCandidate```

Full log here: https://gist.github.com/lakinwecker/932d5d46c6eaf832777c971892f7bfbf

Unsure if I'm using the wrong jdk version, or if a dependency is using the wrong jdk version.   Note that I have only run the `migrate-syntax tv` command so far.

**Comment by adpi2** [comment]
Thanks for reporting this issue.

Unfortunately I could not reproduce it. I tried to run `migrate-syntax` on `OpenJDK 18` and it worked fine. I tried on the newer version of the plugin and the older.

Could you maybe try to run the latest version of the plugin, `0.6.1`, to see if it fixes the error? Otherwise what is your Java distribution and version?
